baseURL: https://raulfiol93.github.io
languageCode: en-us
title: "Fiol's"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  # es:
  #   languageName: Espannol
  #   weight: 3

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
# DefaultContentLanguage: bn

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false


# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background2.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # GitHub repo of your site
  gitRepo: https://github.com/RaulFiol93/raulfiol93.github.io
  # Default branch of your Git repo
  gitBranch: main

  topNavbar:
  maxVisibleSections: 9
  
  # Configure various features of this theme
  features:


    # Enable and configure portfolio
    portfolio:
      enable: false

    # Enable and configure blog posts
    blog:
      enable: false
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true


    # Enable Analytics
    analytics:
      enabled: false
      services:
        # Google Analytics
        google:
          id: G-H4LBG7NDFZ

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    # Show tags under the post title
    # tags:
    #   enable: true

    # Specify whether to show flag in the language selector. Default is true.
    flags:
      enable: true
      # # If you want to use different country flag for a language, specify them here.
      # flagOverwrites:
      #   - languageCode: en
      #     countryCode: us

    # Enable this to use `embed-pdf` shortcode.
    embedpdf:
      enable: false


    # Enable to use custom syntax highlight
    # Please note, Hugo comes with it's own html based syntax highlighter.
    # Your code block will still be syntax highlighted by hugo.
    # For more details: https://gohugo.io/content-management/syntax-highlighting/
    # To disable Hugo's builtin syntax highlight,
    # see: https://gohugo.io/getting-started/configuration-markup#highlight
    # ```
    # # config.yaml
    # markup:
    #   # this disables hugo's syntax highlighting.
    #   codeFences: false
    # ```
    syntaxHighlight:
      enable: true
      services:
        hljs:
          # see: https://highlightjs.readthedocs.io/en/latest/api.html#configure
          noHighlightRe: /^no-highlight$/i

